version: '3.8'

services:
  web:
    build: ./
    command: gunicorn _core.wsgi:application --bind 0.0.0.0:8000 -w3
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rssuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=rssdb

volumes:
  postgres_data: